export const mockedMemes = [
  {
    id: 1,
    title: "Ватрушки",
    description: "Собака кароче с ватрушками",
    owner: "Даша Шу",
    imageUrl: "/vatrushki.png",
    initialLikes: 5,
  },
  {
    id: 2,
    title: "Рыба",
    description: "Рыба типа карась с сигаретой и в кедах конверсах",
    owner: "Даша Шу",
    imageUrl: "/fish.png",
    initialLikes: 6,
  },
  {
    id: 3,
    title: "Ноги прикол",
    description: "Ноги такие типа пальцами показывают пис (2)",
    owner: "Даша Шу",
    imageUrl: "/foots.jpg",
    initialLikes: 100,
  },
  {
    id: 4,
    title: "Миньен на гироскутере",
    description:
      "Миньен стоит на гироскутере в крутой позе ногу так на стену поставил",
    owner: "Даша Шу",
    imageUrl: "/minion.jpg",
    initialLikes: 52,
  },
  {
    id: 5,
    title: "Вацап лошадь",
    description: "Вацап лошадь",
    owner: "Даша Шу",
    imageUrl: "/whatsapp.jpg",
    initialLikes: 0,
  },
  {
    id: 6,
    title: "Червяк даша",
    description: "Червяк и написано dasha",
    owner: "Даша Шу",
    imageUrl: "/worm.jpg",
    initialLikes: 3,
  },
  {
    id: 7,
    title: "Хотите верьте хотите нет",
    description:
      "Мужик рыбачит на заднем фоне дельфины из воды выпригивают и написано хотите верьет хотите нет",
    owner: "Даша Шу",
    imageUrl: "/verte.jpg",
    initialLikes: 32,
  },
  {
    id: 8,
    title: "креветка круто",
    description:
      "креветка с баскетбольным кольцом играет в баскетбол и написано круто и там еще акула",
    owner: "Даша Шу",
    imageUrl: "/cool.jpg",
    initialLikes: 3,
  },
  {
    id: 9,
    title: "тони дауни",
    description:
      "тони старк железный человек роберт дауни младший летит в небе в странной позе и сзади грузовик самосвал на шариках летит",
    owner: "Даша Шу",
    imageUrl: "/stark.jpg",
    initialLikes: 0,
  },
  {
    id: 1,
    title: "Ватрушки",
    description: "Собака кароче с ватрушками",
    owner: "Даша Шу",
    imageUrl: "/vatrushki.png",
    initialLikes: 5,
  },
  {
    id: 2,
    title: "Рыба",
    description: "Рыба типа карась с сигаретой и в кедах конверсах",
    owner: "Даша Шу",
    imageUrl: "/fish.png",
    initialLikes: 6,
  },
  {
    id: 3,
    title: "Ноги прикол",
    description: "Ноги такие типа пальцами показывают пис (2)",
    owner: "Даша Шу",
    imageUrl: "/foots.jpg",
    initialLikes: 100,
  },
  {
    id: 4,
    title: "Миньен на гироскутере",
    description:
      "Миньен стоит на гироскутере в крутой позе ногу так на стену поставил",
    owner: "Даша Шу",
    imageUrl: "/minion.jpg",
    initialLikes: 52,
  },
  {
    id: 5,
    title: "Вацап лошадь",
    description: "Вацап лошадь",
    owner: "Даша Шу",
    imageUrl: "/whatsapp.jpg",
    initialLikes: 0,
  },
  {
    id: 6,
    title: "Червяк даша",
    description: "Червяк и написано dasha",
    owner: "Даша Шу",
    imageUrl: "/worm.jpg",
    initialLikes: 3,
  },
  {
    id: 7,
    title: "Хотите верьте хотите нет",
    description:
      "Мужик рыбачит на заднем фоне дельфины из воды выпригивают и написано хотите верьет хотите нет",
    owner: "Даша Шу",
    imageUrl: "/verte.jpg",
    initialLikes: 32,
  },
  {
    id: 8,
    title: "креветка круто",
    description:
      "креветка с баскетбольным кольцом играет в баскетбол и написано круто и там еще акула",
    owner: "Даша Шу",
    imageUrl: "/cool.jpg",
    initialLikes: 3,
  },
  {
    id: 9,
    title: "тони дауни",
    description:
      "тони старк железный человек роберт дауни младший летит в небе в странной позе и сзади грузовик самосвал на шариках летит",
    owner: "Даша Шу",
    imageUrl: "/stark.jpg",
    initialLikes: 0,
  },
  {
    id: 1,
    title: "Ватрушки",
    description: "Собака кароче с ватрушками",
    owner: "Даша Шу",
    imageUrl: "/vatrushki.png",
    initialLikes: 5,
  },
  {
    id: 2,
    title: "Рыба",
    description: "Рыба типа карась с сигаретой и в кедах конверсах",
    owner: "Даша Шу",
    imageUrl: "/fish.png",
    initialLikes: 6,
  },
  {
    id: 3,
    title: "Ноги прикол",
    description: "Ноги такие типа пальцами показывают пис (2)",
    owner: "Даша Шу",
    imageUrl: "/foots.jpg",
    initialLikes: 100,
  },
  {
    id: 4,
    title: "Миньен на гироскутере",
    description:
      "Миньен стоит на гироскутере в крутой позе ногу так на стену поставил",
    owner: "Даша Шу",
    imageUrl: "/minion.jpg",
    initialLikes: 52,
  },
  {
    id: 5,
    title: "Вацап лошадь",
    description: "Вацап лошадь",
    owner: "Даша Шу",
    imageUrl: "/whatsapp.jpg",
    initialLikes: 0,
  },
  {
    id: 6,
    title: "Червяк даша",
    description: "Червяк и написано dasha",
    owner: "Даша Шу",
    imageUrl: "/worm.jpg",
    initialLikes: 3,
  },
  {
    id: 7,
    title: "Хотите верьте хотите нет",
    description:
      "Мужик рыбачит на заднем фоне дельфины из воды выпригивают и написано хотите верьет хотите нет",
    owner: "Даша Шу",
    imageUrl: "/verte.jpg",
    initialLikes: 32,
  },
  {
    id: 8,
    title: "креветка круто",
    description:
      "креветка с баскетбольным кольцом играет в баскетбол и написано круто и там еще акула",
    owner: "Даша Шу",
    imageUrl: "/cool.jpg",
    initialLikes: 3,
  },
  {
    id: 9,
    title: "тони дауни",
    description:
      "тони старк железный человек роберт дауни младший летит в небе в странной позе и сзади грузовик самосвал на шариках летит",
    owner: "Даша Шу",
    imageUrl: "/stark.jpg",
    initialLikes: 0,
  },
  {
    id: 1,
    title: "Ватрушки",
    description: "Собака кароче с ватрушками",
    owner: "Даша Шу",
    imageUrl: "/vatrushki.png",
    initialLikes: 5,
  },
  {
    id: 2,
    title: "Рыба",
    description: "Рыба типа карась с сигаретой и в кедах конверсах",
    owner: "Даша Шу",
    imageUrl: "/fish.png",
    initialLikes: 6,
  },
  {
    id: 3,
    title: "Ноги прикол",
    description: "Ноги такие типа пальцами показывают пис (2)",
    owner: "Даша Шу",
    imageUrl: "/foots.jpg",
    initialLikes: 100,
  },
  {
    id: 4,
    title: "Миньен на гироскутере",
    description:
      "Миньен стоит на гироскутере в крутой позе ногу так на стену поставил",
    owner: "Даша Шу",
    imageUrl: "/minion.jpg",
    initialLikes: 52,
  },
  {
    id: 5,
    title: "Вацап лошадь",
    description: "Вацап лошадь",
    owner: "Даша Шу",
    imageUrl: "/whatsapp.jpg",
    initialLikes: 0,
  },
  {
    id: 6,
    title: "Червяк даша",
    description: "Червяк и написано dasha",
    owner: "Даша Шу",
    imageUrl: "/worm.jpg",
    initialLikes: 3,
  },
  {
    id: 7,
    title: "Хотите верьте хотите нет",
    description:
      "Мужик рыбачит на заднем фоне дельфины из воды выпригивают и написано хотите верьет хотите нет",
    owner: "Даша Шу",
    imageUrl: "/verte.jpg",
    initialLikes: 32,
  },
  {
    id: 8,
    title: "креветка круто",
    description:
      "креветка с баскетбольным кольцом играет в баскетбол и написано круто и там еще акула",
    owner: "Даша Шу",
    imageUrl: "/cool.jpg",
    initialLikes: 3,
  },
  {
    id: 9,
    title: "тони дауни",
    description:
      "тони старк железный человек роберт дауни младший летит в небе в странной позе и сзади грузовик самосвал на шариках летит",
    owner: "Даша Шу",
    imageUrl: "/stark.jpg",
    initialLikes: 0,
  },
];
